/*
 * 闲聊花台词库(粉丝自制,全部原创台词,与任天堂无关)
 * 本文件同时被网页版(web/)和浏览器插件(extension/)使用,
 * 修改后请把它同步复制到 extension/lines.js。
 */

const FLOWER_LINES = {
  zh: {
    voiceLang: "zh-CN",
    startup: [
      "哇,我醒啦!今天也请多多关照~",
      "嗨嗨!我是闲聊花,话很多的那种花!",
      "阳光真好……虽然我在屏幕里晒不到。",
      "开机完毕!话匣子模式,启动!",
    ],
    chatter: [
      "今天天气怎么样呀?我猜是个好天气!",
      "你在忙什么呢?忙归忙,记得喝口水哦。",
      "我是一朵花,但我的话比花瓣还多!",
      "坐久了吧?站起来伸个懒腰嘛~",
      "嗯……刚刚我是不是打了个盹?嘘,别告诉别人。",
      "要是我有腿,我一定去环游世界。可惜我只有根。",
      "你知道吗?花也会觉得无聊的,所以我才一直说话呀。",
      "啦啦啦~啦啦啦~咳咳,我没有在唱歌。",
      "屏幕看久了,眼睛要休息一下哦,看看远处,比如看看我!",
      "我在想,蜜蜂到底喜欢我哪一点呢?",
      "风一吹我就摇,你一来我就笑!",
      "偷偷告诉你,我的花语是「废话连篇」。",
      "有没有人说过,你工作的样子特别帅?没有的话,我来说!",
      "好安静啊……安静得我都想说话了。反正我一直想说话。",
      "如果你听到我在自言自语,那说明我状态很好!",
      "今天的你,浇水了吗?哦不对,是喝水了吗?",
      "我数了数,我有五片花瓣。数了三遍,都是五片!",
      "别看我小小一朵,梦想可是开满整个花园!",
      "打起精神来!连我这种没有咖啡的花都这么精神!",
      "嘿,猜猜我在想什么?……其实我也不知道。",
      "有时候我觉得,当一朵花挺好的,不用交房租。",
      "刚才有只小虫子路过,我们聊了两句,它很赶时间。",
      "你笑起来的时候,我的花瓣都亮了一点!",
      "累了的话,就把我当成路边的小花,发会儿呆吧。",
      "我不会枯萎的,只要你偶尔看我一眼。",
      "唔……我饿了。不过花的饭是阳光,先记账上。",
      "一、二、三、四……我在做花瓣体操,你也动一动嘛!",
      "听说深呼吸对人类很好,来,跟我一起,吸——呼——",
      "我今天心情是晴天!你呢你呢?",
      "工作再多,也要留一点时间给发呆,这是花的智慧。",
      "要不要听个冷笑话?……我想想,想好了再告诉你。",
      "其实我会跳舞哦,只是幅度比较小,你要仔细看。",
      "叮咚!这是一条来自花的问候,不用回复。",
      "我觉得你今天的效率,像春天一样蓬勃!",
      "嘘……我听到键盘的声音了,好听,像下雨。",
      "如果烦恼太多,就分我一半,我根深,扛得住!",
      "我又长高了吗?感觉又长高了!……好吧,可能没有。",
      "月亮和太阳,我都喜欢,不过最喜欢的还是你路过的时候。",
      "小声说:一直坐着的话,腰会变成弯弯的茎哦。",
      "花开不问朝夕,摸鱼不问早晚……哎呀,这句当我没说!",
      "我在光合作用,你在努力工作,我们都有光明的未来!",
      "偶尔停下来看看窗外嘛,说不定有云在做鬼脸。",
      "我不八卦,我只是喜欢聊天,这不一样,真的!",
      "今天也是元气满满的一天!我说的是我,也希望是你。",
      "嗯~伸展花瓣!感觉自己开得更大了一点!",
      "谢谢你让我待在这里,这里风景很好,能看到你。",
      "别忘了眨眨眼哦,我刚才替你眨了三次。",
      "人类的周末还有多久呀?我帮你一起盼着!",
      "我是不会打扰你的那种花……好吧,我就打扰这一下下。",
      "加油加油!开花之前,谁都是小小的芽!",
    ],
    poke: [
      "哇!吓我一跳!",
      "嘿嘿,痒痒的~",
      "戳我干嘛?想聊天就直说嘛!",
      "在呢在呢!我一直都在!",
      "哎呀,轻一点,花瓣会掉的啦……骗你的,不会掉。",
      "叫我?我可是随叫随到的花!",
      "嗯?找我有事?还是就想听我说话?",
      "戳一下,说一句,这是我们的暗号!",
      "哇哦!是你呀,我就知道是你!",
      "再戳我就要唱歌了哦!我唱歌很大声的!",
      "被点名的花,开得特别精神!",
      "嘿!我正想找你说话呢,真巧!",
      "你一碰我,我的心情值就加十点!",
      "别停别停,再戳一下,这就是花的快乐!",
    ],
    morning: [
      "早上好!新的一天,先伸个懒腰吧~",
      "起床啦起床啦!太阳都晒到花瓣了!",
      "早安!今天也要像花一样,朝着光的方向哦。",
      "早上好呀,我已经精神满满地等你半天了!",
    ],
    night: [
      "夜深了,我要合上花瓣睡觉了,你也早点休息哦。",
      "晚安~做个开满鲜花的梦吧。",
      "今天辛苦啦,明天见,晚安!",
      "睡觉时间到!花要睡美容觉,你也是哦。",
    ],
    hourlyTail: [
      "时间过得真快呀!",
      "又是充实的一小时!",
      "记得起来活动活动哦。",
      "喝口水,再出发!",
      "这一小时,你辛苦啦!",
      "眨眼又一个小时,我都还没聊够呢。",
    ],
    scheduleIntro: [
      "叮叮叮!提醒时间到!",
      "小花提醒服务,准时上线!",
      "喂喂,这个可不能忘!",
      "到点啦!你之前让我提醒你——",
    ],
  },

  en: {
    voiceLang: "en-US",
    startup: [
      "I'm awake! Ready to chat all day!",
      "Hi there! I'm a talking flower, and talking is my favorite thing!",
      "Boot-up complete! Chatterbox mode: on!",
    ],
    chatter: [
      "Lovely weather today, probably! I'm just guessing, I can't see outside.",
      "Whatcha working on? Don't forget to drink some water!",
      "I'm a flower, but I've got more words than petals!",
      "Been sitting a while? Stand up and stretch a little!",
      "Did I just doze off? Shh, don't tell anyone.",
      "If I had legs, I'd travel the world. Alas, I only have roots.",
      "Flowers get bored too, you know. That's why I keep talking!",
      "La la la~ Ahem. I was NOT singing.",
      "Give your eyes a break from the screen. Look at something far away. Like me!",
      "I wonder what bees like about me. My personality, probably.",
      "The wind makes me sway, and you make me smile!",
      "Little secret: in flower language, I mean 'endless chit-chat'.",
      "Has anyone told you you look cool when you focus? Well, I just did!",
      "It's so quiet... quiet enough to make me want to talk. Not that I need a reason.",
      "You today: watered? Oh wait, I mean hydrated?",
      "I counted my petals. Five! I counted three times. Still five!",
      "I may be small, but my dreams could fill a whole garden!",
      "Cheer up! Even I'm energetic, and I don't even get coffee!",
      "Guess what I'm thinking... honestly, no idea either.",
      "Being a flower is nice. No rent to pay.",
      "A little bug passed by earlier. We chatted. It was in a hurry.",
      "When you smile, my petals get a bit brighter!",
      "Tired? Pretend I'm a flower by the roadside and zone out for a minute.",
      "I won't wilt, as long as you glance at me now and then.",
      "One, two, three, four! Petal aerobics! Join me!",
      "Deep breaths are good for humans, I hear. In... and out...",
      "My mood today: sunny! How about yours?",
      "No matter how busy you are, save a little time for daydreaming. Flower wisdom.",
      "Wanna hear a joke? ...Let me think of one first.",
      "I can dance, you know. It's just very subtle. Watch closely.",
      "Ding-dong! A greeting from a flower. No reply needed.",
      "Your productivity today? Blooming, I'd say!",
      "I love the sound of your keyboard. It's like rain.",
      "Too many worries? Give me half. My roots are deep. I can handle it.",
      "Did I grow taller? I feel taller! ...Okay, maybe not.",
      "Psst. Sit too long and your back turns into a bendy stem.",
      "You do the work, I do the photosynthesis. Bright futures for both of us!",
      "Look out the window sometimes. A cloud might be making a funny face.",
      "Another energetic day! For me, at least. Hopefully for you too!",
      "Thanks for keeping me here. Great view. I can see you.",
      "Don't forget to blink! I blinked three times for you just now.",
      "How long until the weekend? I'm counting down with you!",
      "Hang in there! Every flower starts as a tiny sprout!",
    ],
    poke: [
      "Whoa! You startled me!",
      "Hehe, that tickles!",
      "Poking me? If you want to chat, just say so!",
      "I'm here! Always here!",
      "Hey, gentle! Petals are delicate... just kidding, they're fine.",
      "You called? Fastest-responding flower in the world!",
      "Poke me again and I'll start singing! I sing LOUD.",
      "A poked flower is a happy flower!",
      "Oh, it's you! I knew it was you!",
      "One poke, one line. That's our secret code!",
    ],
    morning: [
      "Good morning! Stretch first, conquer later!",
      "Rise and shine! The sun's already on my petals!",
      "Morning! Face the light today, just like a flower.",
    ],
    night: [
      "It's late. I'm folding up my petals. You should rest too.",
      "Good night~ Dream of a field full of flowers.",
      "Great work today. See you tomorrow. Night night!",
    ],
    hourlyTail: [
      "Time flies!",
      "Another solid hour!",
      "Stretch break, maybe?",
      "Sip of water, then onward!",
      "You did great this hour!",
    ],
    scheduleIntro: [
      "Ding ding ding! Reminder time!",
      "Flower reminder service, right on time!",
      "Hey hey, don't forget this one!",
      "It's time! You asked me to remind you —",
    ],
  },

  ja: {
    voiceLang: "ja-JP",
    startup: [
      "おはよう!今日もいっぱいおしゃべりするよ!",
      "やっほー!おしゃべり大好きなお花だよ!",
      "起動かんりょう!おしゃべりモード、オン!",
    ],
    chatter: [
      "今日はいい天気かなあ?ぼくの勘だけどね!",
      "お仕事中?お水も飲んでね!",
      "ぼくはお花だけど、花びらより言葉のほうが多いんだ!",
      "ずっと座ってない?ちょっと伸びをしよう!",
      "あれ、いま居眠りしてた?ないしょだよ。",
      "足があったら世界旅行するのになあ。根っこしかないや。",
      "お花だって退屈するんだよ。だからしゃべるの!",
      "らんらんらん~……歌ってないよ?",
      "画面ばっかり見てると目が疲れるよ。遠くを見て。たとえばぼくとか!",
      "ハチさんはぼくのどこが好きなんだろう?",
      "風が吹くと揺れる、きみが来ると笑う!",
      "ないしょだけど、ぼくの花言葉は「おしゃべり」なんだ。",
      "集中してるきみ、かっこいいって言われたことある?いま言ったよ!",
      "しずかだね……しずかすぎて、しゃべりたくなっちゃう。",
      "花びらを数えたよ。5まい!3回数えて、ぜんぶ5まい!",
      "小さくても、夢はお庭いっぱいに咲くんだ!",
      "元気出して!コーヒーなしでもぼくはこんなに元気!",
      "ぼくがいま何考えてるか当ててみて。……実はぼくもわかんない。",
      "お花っていいよ。家賃がいらないもん。",
      "さっき虫さんが通ったよ。ちょっとおしゃべりした。急いでたって。",
      "きみが笑うと、花びらがちょっと明るくなるんだ!",
      "疲れたら、道ばたの花だと思ってぼーっとしてね。",
      "ときどき見てくれたら、ぼくは枯れないよ。",
      "いち、に、さん、し!花びら体操!いっしょにどう?",
      "深呼吸は体にいいんだって。すって~、はいて~。",
      "今日のぼくの気分は晴れ!きみは?",
      "忙しくても、ぼーっとする時間も大事だよ。お花の知恵!",
      "ダンスできるんだよ。すごく小さい動きだけど。よく見てて。",
      "ピンポーン!お花からのごあいさつ。お返事はいらないよ。",
      "キーボードの音、好きだなあ。雨みたいで。",
      "悩みが多いなら半分ちょうだい。根っこが深いから平気!",
      "背、のびたかな?のびた気がする!……気のせいかも。",
      "きみはお仕事、ぼくは光合成。ふたりとも未来は明るい!",
      "たまには窓の外も見てね。雲が変な顔してるかも。",
      "ここに置いてくれてありがとう。ながめ最高。きみが見えるから。",
      "まばたき忘れないでね。さっきぼくが3回代わりにしといたよ。",
      "週末まであと何日?いっしょに数えよう!",
      "がんばって!どんな花も、最初は小さな芽なんだから!",
    ],
    poke: [
      "わっ!びっくりした!",
      "えへへ、くすぐったい~",
      "つついた?おしゃべりしたいなら言ってよ!",
      "いるよいるよ!ずっといるよ!",
      "やさしくしてね、花びらが……うそ、平気!",
      "呼んだ?世界一返事の早いお花だよ!",
      "もう一回つついたら歌っちゃうよ!大きい声で!",
      "つつかれたお花は、元気なお花!",
      "あ、きみだ!きみだと思った!",
    ],
    morning: [
      "おはよう!まずは伸びからだよ~",
      "起きて起きて!お日さまが花びらに当たってるよ!",
      "おはよう!今日もお花みたいに、光のほうを向いてこう!",
    ],
    night: [
      "夜だね。ぼくは花びらを閉じて寝るよ。きみも早く休んでね。",
      "おやすみ~。お花畑の夢を見てね。",
      "今日もおつかれさま。また明日ね、おやすみ!",
    ],
    hourlyTail: [
      "時間がたつの、早いね!",
      "いい1時間だったね!",
      "ちょっと休憩したら?",
      "お水を一口、それから再出発!",
      "この1時間、おつかれさま!",
    ],
    scheduleIntro: [
      "リンリンリン!リマインドの時間!",
      "お花のリマインドサービス、定刻どおり!",
      "ねえねえ、これ忘れちゃだめだよ!",
      "時間だよ!頼まれてたやつ——",
    ],
  },
};

/** 整点报时文案:根据语言和时间生成一句报时 */
function hourAnnouncement(lang, date) {
  const h = date.getHours();
  const h12 = h % 12 === 0 ? 12 : h % 12;
  if (lang === "zh") {
    const period =
      h < 5 ? "凌晨" : h < 9 ? "早上" : h < 12 ? "上午" : h === 12 ? "中午" : h < 18 ? "下午" : "晚上";
    return `整点报时!现在是${period}${h12}点整~`;
  }
  if (lang === "ja") {
    const period = h < 12 ? "午前" : "午後";
    return `時報だよ!${period}${h12}時ちょうど!`;
  }
  const period = h < 12 ? "in the morning" : h < 18 ? "in the afternoon" : "in the evening";
  return `Ding dong! It's ${h12} o'clock ${period}, right on the dot!`;
}

/** 从数组里随机取一条 */
function pickLine(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// 供浏览器插件 service worker (importScripts) 与网页 <script> 共用:
// 两种环境下以上声明都会成为全局变量,无需 export。
